#postgres docker compose for development
version: "3.1"
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
      #init db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  sqladminer:
    image: adminer
    container_name: sqladminer
    ports:
      - "1338:8080"
